name: macos build
run-name: build runner on macos 🚀

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    paths:
      - 'cmake/**'
      - 'include/**/*.h'
      - 'src/**/*.cc'
      - 'examples/**'
      - 'scripts/**'
      - 'CMakeLists.txt'
      - '.github/workflows/macos-build.yaml'

jobs:
  build-amd-macos:
    strategy:
      matrix:
        os: ["macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: |
          bash -c "cd ${{ github.workspace }} && ./scripts/build.sh"
